introduced b.echo and autoreply

diff --git a/.bush/lib b/.bush/lib
--- a/.bush/lib
+++ b/.bush/lib
@@ -1,3 +1,5 @@
+BUSH=${BUSH:-$(dirname ${BASH_SOURCE[0]})}
+
 b.files () {
     find -L "$1" \( -type f -not -name "*-" -print \) -or \( -type d -name "*-" -prune \)  | uniq | rev | sort | rev
 }
@@ -21,26 +23,36 @@ b.stopwatch () {
 } 
 
 
-BUSH_IOMODE="(1line)"
+BUSH_IOMODE=${BUSH_IOMODE-"(1line)"}
+
+b.oneline? () {
+    [[ "$BUSH_IOMODE" == *"(1line)"* ]]
+}
 
 b.morelines () { 
-    [[ "$BUSH_IOMODE" == *"(1line)"* ]] && echo "↓"
+    b.oneline? && echo "↓"
     BUSH_IOMODE=${BUSH_IOMODE/"(1line)"/}
 }
 
 b.oneline () {
-    [[ "$BUSH_IOMODE" == *"(1line)"* ]] && return 0
+    b.oneline? && return 0
     BUSH_IOMODE="$BUSH_IOMODE(1line)"
     return 1
 }
 
+b.linesep () { # https://stackoverflow.com/a/15184414/1964213 
+    b.oneline? && echo -n " " || echo    
+}
 
-b.linesep () { # >>> $() swallows trailing newlines, so $(b.linesep) won't work
-               # https://stackoverflow.com/a/15184414/1964213 
-    [[ "$b_1linemode" ]] && echo -n " " || echo    
+b.echo () {
+    echo -n $@
+    b.linesep
 }
 
 b.yes? () {
+    [[ "$BUSH_AUTOREPLY" =~ ^[Yy]$ ]] && return 0
+    [[ "$BUSH_AUTOREPLY" ]] && return 1
+
     local prompt="${1:-"Continue?"}"
     read -p "$prompt " -n 1 -r
     b.linesep
@@ -53,7 +65,6 @@ b.have? () {
     [[ "$1" == */ ]] && [[ -d "$1" ]] && return 0
     [[ "$1" == /* ]] && [[ -r "$1" ]] && return 0
     [[ "$1" == ./* ]] && [[ -r "$1" ]] && return 0
-    echo -n "Missing $1!"
-    b.linesep 
+    b.echo "Missing $1!"
     return 1
 } 
